//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostic
    {
        public int DiagnosticId { get; set; }
        public int AreaId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string PicturePath1 { get; set; }
        public string PicturePath2 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Area Area { get; set; }
    }
}
