//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.InitialDentalNotes = new HashSet<InitialDentalNote>();
            this.ProgressNotes = new HashSet<ProgressNote>();
        }
    
        public int PatientId { get; set; }
        public string FullName { get; set; }
        public bool IsDCM { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<InitialDentalNote> InitialDentalNotes { get; set; }
        public virtual ICollection<ProgressNote> ProgressNotes { get; set; }
        public virtual User User { get; set; }
    }
}
